apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: pi0s-cluster
spec:
  hosts:
    - role: controller
      installFlags:
        - --debug
      ssh:
        address: "pi01.pangarabbit.com"
        user: tvl
        port: 22
        keyPath: "~/.ssh/pinodes"
  k0s:
    version: 1.31.2+k0s.0
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: ClusterConfig
      metadata:
        name: pi0s-cluster
      spec:
        api:
          address: 192.168.0.48
          port: 6443
          k0sApiPort: 9443
          externalAddress: pi0s.pangarabbit.com
          sans:
            - 192.168.0.48
        storage:
          type: etcd
          etcd:
            peerAddress: 192.168.0.48
        network:
          podCIDR: 10.244.0.0/16
          serviceCIDR: 10.96.0.0/12
          provider: kuberouter
        podSecurityPolicy:
          defaultPolicy: 00-k0s-privileged
        telemetry:
          enabled: false
        installConfig:
          users:
            etcdUser: etcd
            kineUser: kube-apiserver
            konnectivityUser: konnectivity-server
            kubeAPIserverUser: kube-apiserver
            kubeSchedulerUser: kube-scheduler
        images:
          konnectivity:
            image: us.gcr.io/k8s-artifacts-prod/kas-network-proxy/proxy-agent
            version: v0.0.16
          metricsserver:
            image: gcr.io/k8s-staging-metrics-server/metrics-server
            version: v0.3.7
          kubeproxy:
            image: k8s.gcr.io/kube-proxy
            version: v1.21.2
          coredns:
            image: docker.io/coredns/coredns
            version: 1.7.0
          calico:
            cni:
              image: docker.io/calico/cni
              version: v3.18.1
            node:
              image: docker.io/calico/node
              version: v3.18.1
            kubecontrollers:
              image: docker.io/calico/kube-controllers
              version: v3.18.1
          kuberouter:
            cni:
              image: docker.io/cloudnativelabs/kube-router
              version: v1.2.1
            cniInstaller:
              image: quay.io/k0sproject/cni-node
              version: 0.1.0
          default_pull_policy: IfNotPresent
        konnectivity:
          agentPort: 8132
          adminPort: 8133
